name: Integración Continua

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Dar permisos a Maven Wrapper
        run: chmod +x mvnw

      - name: Compilar aplicación (demo)
        run: ./mvnw clean install

      - name: Ejecutar pruebas (demo)
        run: ./mvnw test