name: CD to Render

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Dar permisos a Maven Wrapper
        run: chmod +x mvnw

      - name: Compilar y ejecutar pruebas
        run: |
          ./mvnw clean install
          ./mvnw test

      - name: Activar despliegue en Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
